# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

defaults_working_directory: &defaults_working_directory
  working_directory: ~/repo

defaults_docker_node: &defaults_docker_node
  docker:
    - image: circleci/openjdk:8-jdk

defaults_Environment: &defaults_environment
  environment:
    MAVEN_OPTS: -Xmx3200m
    WSO2_SERVER_VERSION: "5.7.0"

defaults_build_docker_login: &defaults_build_docker_login
  name: Login to Docker Hub
  command: |
    docker login -u $DOCKER_USER -p $DOCKER_PASS $DOCKER_ORG

defaults_build_docker_build: &defaults_build_docker_build
  name: Build Docker image
  command: |
    docker build --build-arg WSO2_SERVER_VERSION=$WSO2_SERVER_VERSION --no-cache -t $DOCKER_ORG/$CIRCLE_PROJECT_REPONAME-$WSO2_SERVER_VERSION:$CIRCLE_TAG -t $DOCKER_ORG/$CIRCLE_PROJECT_REPONAME-$WSO2_SERVER_VERSION:$RELEASE_TAG .

defaults_build_docker_publish: &defaults_build_docker_publish
  name: Publish Docker image $CIRCLE_TAG & Latest tag to Docker Hub
  command: |
    echo "Publishing $DOCKER_ORG/$CIRCLE_PROJECT_REPONAME-$WSO2_SERVER_VERSION:$CIRCLE_TAG"
    docker push $DOCKER_ORG/$CIRCLE_PROJECT_REPONAME-$WSO2_SERVER_VERSION:$CIRCLE_TAG
    echo "Publishing $DOCKER_ORG/$CIRCLE_PROJECT_REPONAME-$WSO2_SERVER_VERSION:$RELEASE_TAG"
    docker push $DOCKER_ORG/$CIRCLE_PROJECT_REPONAME-$WSO2_SERVER_VERSION:$RELEASE_TAG

jobs:
  
  build:
    <<: *defaults_working_directory
    <<: *defaults_docker_node
    <<: *defaults_environment

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Setup Docker Build
          command: |
            mvn -q -s .circleci/settings.xml dependency:get -Dartifact=mysql:mysql-connector-java:5.1.46:jar -Dtransitive=false -Ddest=./files/lib/mysql-connector-java-5.1.46.jar
            mvn -q -s .circleci/settings.xml dependency:get -Dartifact=org.dnsjava:dnsjava:2.1.8:jar -Dtransitive=false -Ddest=./files/lib/dnsjava-2.1.8.jar            
            mvn -q -s .circleci/settings.xml dependency:get -Dartifact=org.wso2.carbon.kubernetes.artifacts:kubernetes-membership-scheme:1.0.5:jar -Dtransitive=false -Ddest=./files/dropins/kubernetes-membership-scheme-1.0.5.jar
            mvn -q -s .circleci/settings.xml dependency:get -Dartifact=org.wso2:wso2is-km:$WSO2_SERVER_VERSION:zip -Dtransitive=false -Ddest=./files/wso2is-km-$WSO2_SERVER_VERSION.zip
            unzip -o -q ./files/wso2is-km-$WSO2_SERVER_VERSION.zip -d ./files
            
      - run:
          name: Build application Docker image
          command: |       
            rm -f ./files/wso2is-km-$WSO2_SERVER_VERSION.zip
            ls -la ./files/*

      - run:
          name: setup environment vars for SNAPSHOT release
          command: |
            echo 'export RELEASE_TAG=$RELEASE_TAG_PROD' >> $BASH_ENV
      - run:
          <<: *defaults_build_docker_login
      - run:
          <<: *defaults_build_docker_build
      - run:
          <<: *defaults_build_docker_publish

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          context: org-global
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - /.*/
                - /feature*/
                - /bugfix*/
